sylius_fixtures:
    suites:
        default:
            fixtures:
                monsieurbiz_menu:
                    options:
                        custom:
                            -   isSystem: true
                                code: 'main'
                                items:
                                    -   translations:
                                            en_US:
                                                label: 'T-shirts'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/en_US/taxons/category/t-shirts'
                                            fr_FR:
                                                label: 'T-shirts'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/fr_fr/taxons/category/t-shirts'
                                    -   translations:
                                            en_US:
                                                label: 'Caps'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/en_US/taxons/category/caps'
                                            fr_FR:
                                                label: 'Bonnets'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/fr_FR/taxons/category/caps'
                                    -   translations:
                                            en_US:
                                                label: 'Dresses'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/en_US/taxons/category/dresses'
                                            fr_FR:
                                                label: 'Robes'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/fr_FR/taxons/category/dresses'
                                    -   translations:
                                            en_US:
                                                label: 'Jeans'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/en_US/taxons/category/jeans'
                                            fr_FR:
                                                label: 'Jeans'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/fr_FR/taxons/category/jeans'
                            -   isSystem: true
                                code: 'your_store'
                                items:
                                    -   translations:
                                            en_US:
                                                label: 'About'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                            fr_FR:
                                                label: 'A propos'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                    -   translations:
                                            en_US:
                                                label: 'Terms and conditions'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                            fr_FR:
                                                label: 'Termes et conditions'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                    -   translations:
                                            en_US:
                                                label: 'Privacy policy'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                            fr_FR:
                                                label: 'Politique de confidentialité'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                    -   translations:
                                            en_US:
                                                label: 'Contact us'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                            fr_FR:
                                                label: 'Nous contacter'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                            -   isSystem: true
                                code: 'customer_care'
                                items:
                                    -   translations:
                                            en_US:
                                                label: 'Contact us'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                            fr_FR:
                                                label: 'Nous contacter'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                    -   translations:
                                            en_US:
                                                label: 'FAQs'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                            fr_FR:
                                                label: 'FAQs'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                    -   translations:
                                            en_US:
                                                label: 'Delivery & Shipping'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                            fr_FR:
                                                label: 'Expédition et livraison'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                    -   translations:
                                            en_US:
                                                label: 'Return policy'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
                                            fr_FR:
                                                label: 'Politique de retour'
                                                url: 'https://%env(SYLIUS_FIXTURES_HOSTNAME)%/#'
